### ISSUE TITLE
sharedproxy devrel/references/common-shared-flows/logging-v1/sharedflowbundle/ping-v1.xml should be called logging-v1.xml I suppose

### ISSUE THREAD

**Issue by davormilutinovic** [apigee/devrel#207]
Sharedproxy devrel/references/common-shared-flows/logging-v1/sharedflowbundle/ping-v1.xml should be called logging-v1.xml I suppose

**Comment by seymen** [comment]
It is actually more related to monitoring then logging. `Ping` is a specific monitoring response which is generally setup in Apigee with no target endpoint. A successful response from this would signify that the request was successfully received and processed by Apigee. The other monitoring endpoint that goes hand in hand with this is `status` which defines a target endpoint as well. This, therefore, signifies that the request was successfully received/processed by Apigee + the link between Apigee and target is healthy + target was able to successfully process the request and gave a success response. It is a best practice to configure these two monitoring endpoints within a proxy and point monitoring probes to these two endpoints for periodical polling. The failure of one or both will give you an indication of where the problem lies.

**Comment by davormilutinovic** [comment]
Thanks for the explanation and correction of the bundle name.
