### ISSUE TITLE
gcp-sa-auth-shared-flow w/ Multiregional serverless fails 

### ISSUE THREAD

**Issue by vcpmark** [apigee/devrel#532]
references/gcp-sa-auth-shared-flow

When two functions from different regions are behind a GCLB,  only one of the functions will work.

Is this already supported by the shared flow or can it be added?

**Comment by danistrebel** [comment]
Assumptions based on the issue description:
1. Because you're using the shared flow and a GCLB over the built-in Google authentication I assume you're using Apigee Edge?
1. When you say "functions" you mean cloud functions?
1. You're using serverless NEGs as described here: https://cloud.google.com/load-balancing/docs/https/setup-global-ext-https-serverless?

The purpose of this Shared Flow is to create an Access token that can then later be used to call a backed (e.g. a cloud function) whether or not that function is in different regions or not is not relevant assuming you have a service account that is authorized to invoke both functions the two regions.
