### ISSUE TITLE
:grey_question: Unsupported OpenAPI version: 3.0.3

### ISSUE THREAD

**Issue by adriens** [apigee/devrel#682]
# :grey_question: About

We currently are deploying an cloud based APIGEE instance on GCP AUS for [OPT Nouvelle Caledonie](https://github.com/opt-nc?view_as=public), and yesterday, while trying to import an API spec from `yaml` we got the following message:

```
Unsupported OpenAPI version: 3.0.3. 
Swagger parser only supports versions 3.0.0, 3.0.1, 3.0.2
```

![image](https://github.com/apigee/devrel/assets/5235127/cfa614b3-065a-4ef4-bf3e-1ddc8c9193c5)

# :dart: Question

Can you tell us when [`3.0.3`](https://swagger.io/specification/v3/) will be supported ?

Thank you in advance for your help.

# :bookmark_tabs: Related resources

- [OpenAPI Specification `Version 3.0.3`](https://swagger.io/specification/v3/)
- [Swagger revision history](https://swagger.io/specification/v3/)

![image](https://github.com/apigee/devrel/assets/5235127/d032bc02-3015-43cd-bc7c-5b95581c9a62)

**Comment by OmidTahouri** [comment]
Hi @adriens -- thanks for the complete details and screenshots. I can inform you that this request is already being tracked, but I'm unable to share any approximate dates for when `3.0.3` or other versions will be supported.

I recommend you raise this and similar requests via a support case, so that demand can be more accurately tracked and the request can be appropriately prioritised.

Thank you.

**Comment by adriens** [comment]
Ho @OmidTahouri , thank you for the feedback. yes, I've submitted this to our partner too. 🙏
